import os
from pathlib import Path

def search(device, user):
	global parlan
	global lan
	os.system(f'df /dev/sd{lan[0]} > flash.txt')
	read_lf()
	sce(lan = lan[0], parlan = 0, device = device, user = user)
	os.system(f'df /dev/sd{lan[0]}{parlan[0]} > flash.txt')
	read_lf()
	sce(lan = lan[0], parlan = parlan[0], device = device, user = user)
	os.system(f'df /dev/sd{lan[0]}{parlan[1]} > flash.txt')
	read_lf()
	sce(lan = lan[0], parlan = parlan[1], device = device, user = user)
	os.system(f'df /dev/sd{lan[0]}{parlan[2]} > flash.txt')
	read_lf()
	sce(lan = lan[0], parlan = parlan[2], device = device, user = user)
	os.system(f'df /dev/sd{lan[1]} > flash.txt')
	read_lf()
	sce(lan = lan[1], parlan = 0, device = device, user = user)
	os.system(f'df /dev/sd{lan[1]}{parlan[0]} > flash.txt')
	read_lf()
	sce(lan = lan[1], parlan = parlan[0], device = device, user = user)
	os.system(f'df /dev/sd{lan[1]}{parlan[1]} > flash.txt')
	read_lf()
	sce(lan = lan[1], parlan = parlan[1], device = device, user = user)
	os.system(f'df /dev/sd{lan[1]}{parlan[2]} > flash.txt')
	read_lf()
	sce(lan = lan[1], parlan = parlan[2], device = device, user = user)
	os.system(f'df /dev/sd{lan[2]} > flash.txt')
	read_lf()
	sce(lan = lan[2], parlan = 0, device = device, user = user)
	os.system(f'df /dev/sd{lan[2]}{parlan[0]} > flash.txt')
	read_lf()
	sce(lan = lan[2], parlan = parlan[0], device = device, user = user)
	os.system(f'df /dev/sd{lan[2]}{parlan[1]} > flash.txt')
	read_lf()
	sce(lan = lan[2], parlan = parlan[1], device = device, user = user)
	os.system(f'df /dev/sd{lan[2]}{parlan[2]} > flash.txt')
	read_lf()
	sce(lan = lan[0], parlan = parlan[2], device = device, user = user)
	os.system(f'df /dev/sd{lan[3]} > flash.txt')
	read_lf()
	sce(lan = 3, parlan = 0, device = device, user = user)
	os.system(f'df /dev/sd{lan[3]}{parlan[0]} > flash.txt')
	read_lf()
	sce(lan = lan[3], parlan = parlan[0], device = device, user = user)
	os.system(f'df /dev/sd{lan[3]}{parlan[1]} > flash.txt')
	read_lf()
	sce(lan = lan[3], parlan = parlan[1], device = device, user = user)
	os.system(f'df /dev/sd{lan[3]}{parlan[2]} > flash.txt')
	read_lf()
	sce(lan = lan[3], parlan = parlan[2], device = device, user = user)
	os.system(f'df /dev/sd{lan[4]} > flash.txt')
	read_lf()
	sce(lan = lan[4], parlan = 0, device = device, user = user)
	os.system(f'df /dev/sd{lan[4]}{parlan[0]} > flash.txt')
	read_lf()
	sce(lan = lan[4], parlan = parlan[0], device = device, user = user)
	os.system(f'df /dev/sd{lan[4]}{parlan[1]} > flash.txt')
	read_lf()
	sce(lan = lan[4], parlan = parlan[1], device = device, user = user)
	os.system(f'df /dev/sd{lan[4]}{parlan[2]} > flash.txt')
	read_lf()
	sce(lan = lan[4], parlan = parlan[2], device = device, user = user)
	os.system(f'df /dev/sd{lan[5]} > flash.txt')
	read_lf()
	sce(lan = lan[5], parlan = 0, device = device, user = user)
	os.system(f'df /dev/sd{lan[5]}{parlan[0]} > flash.txt')
	read_lf()
	sce(lan = lan[5], parlan = parlan[0], device = device, user = user)
	os.system(f'df /dev/sd{lan[5]}{parlan[1]} > flash.txt')
	read_lf()
	sce(lan = lan[5], parlan = parlan[1], device = device, user = user)
	os.system(f'df /dev/sd{lan[5]}{parlan[2]} > flash.txt')
	read_lf()
	sce(lan = lan[5], parlan = parlan[2], device = device, user = user)
	os.system(f'df /dev/sd{lan[6]} > flash.txt')
	read_lf()
	sce(lan = lan[6], parlan = 0, device = device, user = user)
	os.system(f'df /dev/sd{lan[6]}{parlan[0]} > flash.txt')
	read_lf()
	sce(lan = lan[6], parlan = parlan[0], device = device, user = user)
	os.system(f'df /dev/sd{lan[6]}{parlan[1]} > flash.txt')
	read_lf()
	sce(lan = lan[6], parlan = parlan[1], device = device, user = user)
	os.system(f'df /dev/sd{lan[6]}{parlan[2]} > flash.txt')
	read_lf()
	sce(lan = lan[6], parlan = parlan[2], device = device, user = user)
	os.system(f'df /dev/sd{lan[7]} > flash.txt')
	read_lf()
	sce(lan = lan[7], parlan = 0, device = device, user = user)
	os.system(f'df /dev/sd{lan[7]}{parlan[0]} > flash.txt')
	read_lf()
	sce(lan = lan[7], parlan = parlan[0], device = device, user = user)
	os.system(f'df /dev/sd{lan[7]}{parlan[1]} > flash.txt')
	read_lf()
	sce(lan = lan[7], parlan = parlan[1], device = device, user = user)
	os.system(f'df /dev/sd{lan[7]}{parlan[2]} > flash.txt')
	read_lf()
	sce(lan = lan[7], parlan = parlan[2], device = device, user = user)

def read_lf():
	global flashd
	global lf
	flashd = open('flash.txt', 'r')
	lf = flashd.read()

def sce(lan, parlan, device, user):
	global lf
	global a
	if Path(f'/run/media/{user}/').is_dir():
		if lf.count(f'/run/media/{user}/{device}'):
			if parlan == 0:
				ddev = (f'/dev/sd{lan}')
				print(f'/dev/sd{lan}')
				dev_devices = open('dev_device.txt', 'w+')
				dev_devices.write(f'/dev/sd{lan}')
				dev_devices.close()
			else:
				ddev = (f'/dev/sd{lan}{parlan}')
				print(f'/dev/sd{lan}{parlan}')
				dev_devices = open('dev_device.txt', 'w+')
				dev_devices.write(f'/dev/sd{lan}{parlan}')
				dev_devices.close()
			flashd.close()
			os.remove('flash.txt')
		else:
			flashd.close()
			os.remove('flash.txt')
	elif Path(f'/media/{user}/').is_dir():
		if lf.count(f'/media/{user}/{device}'):
			if parlan == 0:
				ddev = (f'/dev/sd{lan}')
				print(f'/dev/sd{lan}')
				dev_devices = open('dev_device.txt', 'w+')
				dev_devices.write(f'/dev/sd{lan}')
				dev_devices.close()
			else:
				ddev = (f'/dev/sd{lan}{parlan}')
				print(f'/dev/sd{lan}{parlan}')
				dev_devices = open('dev_device.txt', 'w+')
				dev_devices.write(f'/dev/sd{lan}{parlan}')
				dev_devices.close()
			flashd.close()
			os.remove('flash.txt')
		else:
			flashd.close()
			os.remove('flash.txt')

lan = ('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
parlan = (1,2,3)
